runtime: nodejs18
instance_class: F2

handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 5